<Project Sdk="Microsoft.NET.Sdk">
   <ItemGroup>
  
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="TwitchLib" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="../TwitchLive.Application/TwitchLive.Application.csproj" />
  </ItemGroup>
</Project>
